/**
 * ============================================================================
 * E-PRESCRIPTION (eRx) GENERATOR UTILITY
 * ============================================================================
 * Dynamically generates a printable, branded Ayush prescription
 * pad including the AI's triage summary and the Physician's notes.
 * Decoupled from React to ensure pure DOM manipulation for the print spooler.
 */

export function generateEPrescription(patient, prescriptionText) {
  if (!patient) return;

  const reportDate = new Date().toLocaleDateString();
  const reportTime = new Date().toLocaleTimeString([], {
    hour: "2-digit",
    minute: "2-digit",
  });

  // Initialize a hidden print window
  const printWindow = window.open("", "_blank");
  if (!printWindow) {
    alert("Popup blocked! Please allow popups to generate the E-Prescription.");
    return;
  }

  // Enterprise-grade print stylesheet and HTML structure
  const htmlContent = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>eRx - ${patient.name}</title>
        <style>
          body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; color: #1f2937; max-width: 800px; margin: 0 auto; line-height: 1.6; }
          .header { text-align: center; border-bottom: 3px solid #16a34a; padding-bottom: 20px; margin-bottom: 30px; }
          .header h1 { margin: 0; color: #14532d; font-size: 28px; text-transform: uppercase; letter-spacing: 1px; }
          .header p { margin: 5px 0 0; color: #16a34a; font-size: 14px; font-weight: bold; text-transform: uppercase; }
          .patient-info { display: grid; grid-template-columns: 1fr 1fr; background: #f0fdf4; padding: 20px; border-radius: 8px; border: 1px solid #bbf7d0; margin-bottom: 30px; }
          .patient-info div { font-size: 13px; margin-bottom: 4px; }
          .patient-info strong { color: #166534; display: inline-block; width: 120px; }
          .triage-summary { background: #f8fafc; border: 1px dashed #cbd5e1; padding: 15px; border-radius: 8px; font-size: 12px; color: #475569; margin-bottom: 30px; }
          .triage-summary strong { color: #0f172a; font-size: 14px; display: block; margin-bottom: 10px; text-transform: uppercase; }
          .rx-section { min-height: 350px; border-left: 3px solid #e5e7eb; padding-left: 25px; position: relative; margin-bottom: 40px; }
          .rx-symbol { font-size: 56px; font-weight: bold; color: #16a34a; font-family: 'Times New Roman', serif; position: absolute; left: -32px; top: -15px; background: white; padding: 10px 0; line-height: 1; }
          .prescription-text { margin-top: 60px; white-space: pre-wrap; font-size: 15px; color: #111827; font-weight: 500; line-height: 1.8; }
          .footer { display: flex; justify-content: space-between; align-items: flex-end; margin-top: 60px; font-size: 14px; color: #1f2937; }
          .signature-box { text-align: center; }
          .signature-line { display: inline-block; width: 250px; border-top: 1px solid #1f2937; padding-top: 8px; font-weight: bold; }
          .verified-badge { font-size: 11px; color: #64748b; font-weight: normal; margin-top: 4px; display: block; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Ministry of Ayush</h1>
          <p>Government of India • Authorized E-Prescription (eRx)</p>
        </div>

        <div class="patient-info">
          <div>
            <div><strong>Patient Name:</strong> ${patient.name}</div>
            <div><strong>Age / Gender:</strong> ${patient.age} Yrs / ${patient.gender}</div>
            <div><strong>ABHA ID:</strong> ${patient.abha_id || "Not Linked"}</div>
          </div>
          <div style="text-align: right;">
            <div><strong>Date:</strong> ${reportDate}</div>
            <div><strong>Time:</strong> ${reportTime}</div>
            <div><strong>OPD Token:</strong> <span style="font-weight:bold; color:#16a34a;">${patient.token_number || "N/A"}</span></div>
          </div>
        </div>

        <div class="triage-summary">
          <strong>AI Triage & Dashavidha Summary</strong>
          Chief Complaint: ${patient.primary_complaint?.replace(/^[🗣️📄🤖]\s*/, "") || "N/A"}<br/>
          Dosha Vikriti: ${patient.dosha_data ? patient.dosha_data.map((d) => `${d.subject} (${d.value}%)`).join(", ") : "Pending Assessment"}
        </div>

        <div class="rx-section">
          <div class="rx-symbol">Rx</div>
          <div class="prescription-text">${prescriptionText ? prescriptionText : "Follow general Ayush dietary and lifestyle protocols as discussed."}</div>
        </div>

        <div class="footer">
          <div style="font-size: 10px; color: #94a3b8; max-width: 300px;">
            Generated by MediKiosk Automated Triage System.<br/>
            Record ID: ${patient.id}
          </div>
          <div class="signature-box">
            <div class="signature-line">
              Attending Physician Signature
              <span class="verified-badge">Digitally verified via MediKiosk Portal</span>
            </div>
          </div>
        </div>
      </body>
    </html>
  `;

  printWindow.document.write(htmlContent);
  printWindow.document.close();
  printWindow.focus();

  // Short delay ensures styles render fully before the browser intercepts with the print dialog
  setTimeout(() => {
    printWindow.print();
    printWindow.close();
  }, 500);
}
